Add files via upload
There are some minor changes required to running this file.
Error:  "Failed to establish database connection.",
    "status": 500